[
  './health.test.js',
  './dashboard.test.js',
  './permissions.test.js',
  './records.test.js',
  './taxonomyRouters.test.js',
  './speciesTraits.test.js',
  './speciesBiomes.test.js',
  './ecosystemBiomes.test.js',
  './ecosystemSpecies.test.js',
].forEach(require);
